name: "ðŸ—ï¸ Build Plugin"

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v3
        id: dotnet
        with:
          dotnet-version: 8.0.x
      - name: Change default dotnet version
        run: |
          echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json
      - name: Install dependencies
        run: dotnet restore -p:UseLocalJellyfinReferences=true
      - name: Build
        run: dotnet build --no-restore -c Release -p:UseLocalJellyfinReferences=true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MetaShark-Release
          path: ./Jellyfin.Plugin.MetaShark/bin/Release/net8.0/Jellyfin.Plugin.MetaShark.dll
      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal
